(in-package :mako)

(ecs:define-component player)

(ecs:define-system move-player
    (:components-ro (player)
     :components-no (wait)
     :components-rw (position tile)
     :enable (not *paused*))
  (setf *player-turn* t)
  (let ((dx 0) (dy 0))
    (when (key-pressed? 'move-up) (decf dy 1))
    (when (key-pressed? 'move-down) (incf dy 1))
    (when (key-pressed? 'move-left) (decf dx 1))
    (when (key-pressed? 'move-right) (incf dx 1))
    (when (and  (or (not (= dx 0))
                    (not (= dy 0)))
                (not (entity-at-tile? 'wall
                                      (+ tile-row dx)
                                      (+ tile-col dy))))
      (assign-wait entity :remaining-time 10)
      (incf tile-row dx)
      (incf tile-col dy)
      (setf tile-hash (a*:encode-integer-coordinates tile-col tile-row)
            position-x (* tile-row +tile-size+)
            position-y (* tile-col +tile-size+))
      (setf *player-turn* nil))))
