(in-package :mako)

(ecs:define-component player)

(ecs:define-system move-player
    (:components-ro (player)
     :components-no (wait)
     :components-rw (position tile)
     :enable (not *paused*))
  (setf *player-turn* t)
  (let ((dx 0.0) (dy 0.0))
    (when (key-pressed? 'move-up) (decf dy 1.0))
    (when (key-pressed? 'move-down) (incf dy 1.0))
    (when (key-pressed? 'move-left) (decf dx 1.0))
    (when (key-pressed? 'move-right) (incf dx 1.0))
    (when (or (not (= dx 0.0))
              (not (= dy 0.0)))
      (assign-wait entity :remaining-time 10)
      (incf position-x (* dx +tile-size+))
      (incf position-y (* dy +tile-size+))
      (setf tile-row (round/tile position-x)
            tile-col (round/tile position-y)
            tile-hash (a*:encode-integer-coordinates tile-col tile-row))
      (setf *player-turn* nil))))
